// Generated by CoffeeScript 1.3.3
var connect, notags, spout1;

module.exports = {
  Spout: require("./spout"),
  Stream: require("./stream"),
  TwitterSpout: require("./twitter-spout"),
  Aggregator: require("./aggregator"),
  SumStat: require("./sum-stat"),
  CountStat: require("./count-stat"),
  SlidingTimeWindow: require("./sliding-window").SlidingTimeWindow
};

spout1 = new module.exports.TwitterSpout({
  "consumer_key": "91SDnh8OqubgzL5tx3fkyw",
  "consumer_secret": "mcoDcN7QKS1MyckSSuOaNEEMeQ0liBpCgy9HYv87eoo",
  "access_token": "1149814628-AtHk0wExCqKCdVkYBgsJL9Mp4T7ftJSPBxUB6zf",
  "access_token_secret": "gDyCcvpPPmKSaolS0ZdUUfnBn9xpyt8jv6q8VWdrwM"
});

notags = 0;

connect = new module.exports.Stream(spout1).project(function(data, cb) {
  var tag, tags, _i, _len, _norm, _ref, _ref1;
  tags = [];
  _ref1 = (_ref = data.entities) != null ? _ref.hashtags : void 0;
  for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
    tag = _ref1[_i];
    _norm = tag.text.toLowerCase();
    if (_norm === "lol" || _norm === "rice") {
      tags.push(_norm);
    }
  }
  return cb(null, {
    id: data != null ? data.id : void 0,
    tags: tags
  });
}).inject(function(data, cb) {
  return cb(null, {
    injectDate: new Date(),
    text: "I love " + (data.tags.join(' '))
  });
}).aggregate(new module.exports.Aggregator({
  window: new module.exports.SlidingTimeWindow(5000),
  stats: [new module.exports.SumStat("id"), new module.exports.CountStat("id")],
  cumulative: false,
  groupBy: "tags",
  emitFrequency: 500
})).sink(function(data) {
  return console.log(data);
});
