// Generated by CoffeeScript 1.3.3
var CountStat, SumStat, connect, spout1, _ref;

_ref = require("./stat"), SumStat = _ref.SumStat, CountStat = _ref.CountStat;

module.exports = {
  Spout: require("./spout"),
  Stream: require("./stream"),
  TwitterSpout: require("./twitter-spout"),
  Aggregator: require("./aggregator"),
  SumStat: SumStat,
  CountStat: CountStat,
  SlidingTimeWindow: require("./sliding-window").SlidingTimeWindow
};

spout1 = new module.exports.TwitterSpout({
  "consumer_key": "91SDnh8OqubgzL5tx3fkyw",
  "consumer_secret": "mcoDcN7QKS1MyckSSuOaNEEMeQ0liBpCgy9HYv87eoo",
  "access_token": "1149814628-AtHk0wExCqKCdVkYBgsJL9Mp4T7ftJSPBxUB6zf",
  "access_token_secret": "gDyCcvpPPmKSaolS0ZdUUfnBn9xpyt8jv6q8VWdrwM"
});

connect = new module.exports.Stream(spout1).project(function(data, cb) {
  var tags, _ref1, _ref2;
  tags = [];
  tags = (_ref1 = data.entities) != null ? (_ref2 = _ref1.hashtags) != null ? _ref2.map(function(tag) {
    return tag.text.toLowerCase();
  }) : void 0 : void 0;
  return cb(null, {
    id: data != null ? data.id : void 0,
    tags: tags
  });
}).inject(function(data, cb) {
  return cb(null, {
    injectDate: new Date(),
    text: "I love " + (data.tags.join(' '))
  });
}).aggregate(new module.exports.Aggregator({
  window: new module.exports.SlidingTimeWindow(5000),
  stats: [new SumStat("id"), new CountStat("id")],
  cumulative: false,
  emitFrequency: 500
})).sink(function(data) {
  return console.log(data);
});
