// Generated by CoffeeScript 1.3.3
var Connect, EventEmitter, ProjectConnect,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

EventEmitter = require('events').EventEmitter;

ProjectConnect = require('./project-connect');

Connect = (function(_super) {

  __extends(Connect, _super);

  function Connect(stream, worker) {
    this.stream = stream;
    this.worker = worker;
    if (!this.stream) {
      return new Error("Stream required");
    }
    Connect.__super__.constructor.call(this);
    this._window = void 0;
    this._handler = void 0;
    this._sinks = [];
    this._connectStream();
  }

  Connect.prototype.execute = function(data) {
    if (!this.worker) {
      return new Error("Worker not definted");
    }
    return this.worker(data);
  };

  Connect.prototype.sink = function(handler) {
    return this._sinks.push(handler);
  };

  Connect.prototype.filter = function(fn) {
    return new ProjectConnect(this.stream, fn);
  };

  Connect.prototype.project = function(fn) {
    return new Connect(this.stream, fn);
  };

  Connect.prototype.inject = function(fn) {
    return new Connect(this.stream, fn);
  };

  Connect.prototype.merge = function() {
    return new Connect(this.stream);
  };

  Connect.prototype.aggregate = function(fn, windowType, subType, lenthOrTime, emitFrequency) {
    return new Connect(this.stream);
  };

  Connect.prototype.join = function() {
    return new Connect(this.stream);
  };

  Connect.prototype._execute = function(data) {
    var sink, _data, _i, _len, _ref, _results;
    _data = this.execute(data);
    this.emit("event:new", _data);
    _ref = this._sinks;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      sink = _ref[_i];
      _results.push(sink(_data));
    }
    return _results;
  };

  Connect.prototype._connectStream = function() {
    var _this = this;
    if (!this.stream) {
      return;
    }
    return this.stream.on("event:new", function(data) {
      return _this._execute(data);
    });
  };

  return Connect;

})(EventEmitter);

module.exports = Connect;
