// Generated by CoffeeScript 1.3.3
var AggregateWorker, Connect, EventEmitter, FilterWorker, InjectWorker, ProjectWorker,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

EventEmitter = require('events').EventEmitter;

ProjectWorker = require('./project-worker');

InjectWorker = require('./inject-worker');

FilterWorker = require('./filter-worker');

AggregateWorker = require('./aggregate-worker');

Connect = (function(_super) {

  __extends(Connect, _super);

  function Connect(stream, worker) {
    this.stream = stream;
    this.worker = worker;
    if (!this.stream) {
      return new Error("Stream required");
    }
    Connect.__super__.constructor.call(this);
    this._sinks = [];
    this._initWorker();
    this._connectStream();
  }

  Connect.prototype._initWorker = function() {
    var _this = this;
    if (!this.worker) {
      return;
    }
    return this.worker.on("event:new", function(data) {
      var sink, _i, _len, _ref, _results;
      _this.emit("event:new", data);
      _ref = _this._sinks;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        sink = _ref[_i];
        _results.push(sink(data));
      }
      return _results;
    });
  };

  Connect.prototype.sink = function(handler) {
    return this._sinks.push(handler);
  };

  Connect.prototype.filter = function(fn) {
    return new Connect(this, new FilterWorker(fn));
  };

  Connect.prototype.project = function(fn) {
    return new Connect(this, new ProjectWorker(fn));
  };

  Connect.prototype.inject = function(fn) {
    return new Connect(this, new InjectWorker(fn));
  };

  Connect.prototype.aggregate = function(aggregator) {
    return new Connect(this, new AggregateWorker(aggregator));
  };

  Connect.prototype.process = function(data) {
    var _this = this;
    return process.nextTick(function() {
      return _this.worker.process(data);
    });
  };

  Connect.prototype._connectStream = function() {
    var _this = this;
    if (!this.stream) {
      return;
    }
    return this.stream.on("event:new", function(data) {
      return _this.process(data);
    });
  };

  return Connect;

})(EventEmitter);

module.exports = Connect;
