// Generated by CoffeeScript 1.3.3
var connect, spout1;

module.exports = {
  Spout: require("./spout"),
  Stream: require("./stream"),
  TwitterSpout: require("./twitter-spout")
};

spout1 = new module.exports.TwitterSpout({
  "consumer_key": "91SDnh8OqubgzL5tx3fkyw",
  "consumer_secret": "mcoDcN7QKS1MyckSSuOaNEEMeQ0liBpCgy9HYv87eoo",
  "access_token": "1149814628-AtHk0wExCqKCdVkYBgsJL9Mp4T7ftJSPBxUB6zf",
  "access_token_secret": "gDyCcvpPPmKSaolS0ZdUUfnBn9xpyt8jv6q8VWdrwM"
});

connect = new module.exports.Stream(spout1).project(function(data) {
  return data.id_str;
}).sink(function(data) {
  return console.log(data);
});
