// Generated by CoffeeScript 1.4.0
var CountStat, SumStat, _ref;

_ref = require("./stat"), SumStat = _ref.SumStat, CountStat = _ref.CountStat;

module.exports = {
  Spout: require("./spout"),
  Stream: require("./stream"),
  TwitterSpout: require("./twitter-spout"),
  Aggregator: require("./aggregator"),
  SumStat: SumStat,
  CountStat: CountStat,
  SlidingTimeWindow: require("./sliding-window").SlidingTimeWindow,
  SingletonWindow: require("./singleton-window")
};
