// Generated by CoffeeScript 1.3.3
var ProjectWorker, Worker,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Worker = require('./worker');

ProjectWorker = (function(_super) {

  __extends(ProjectWorker, _super);

  ProjectWorker.prototype._id = "project_worker";

  function ProjectWorker(operator) {
    this.operator = operator;
    ProjectWorker.__super__.constructor.call(this);
  }

  ProjectWorker.prototype.process = function(data) {
    var _this = this;
    try {
      return this.operator(data, function(error, projected) {
        return _this.emit("data:new", projected);
      });
    } catch (e) {
      if (e) {
        return console.log("" + this._id + " error: " + e);
      }
    }
  };

  return ProjectWorker;

})(Worker);

module.exports = ProjectWorker;
