// Generated by CoffeeScript 1.3.3
var SingletoneWindow, Window,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Window = require('./window');

/*
#
# Windows accumulate a subset of a stream. Each window must
# implement the process method and emit "event:push" and "event:pop" events
#
*/


SingletoneWindow = (function(_super) {

  __extends(SingletoneWindow, _super);

  SingletoneWindow.prototype._key = "singletonwindow";

  function SingletoneWindow() {
    SingletoneWindow.__super__.constructor.call(this);
  }

  SingletoneWindow.prototype.process = function(data) {
    var _this = this;
    return this.store.get(this._key, function(error, value) {
      if (error) {
        throw error;
      }
      if (value) {
        _this.emit("data:pop", [value]);
      }
      return _this.store.put(_this._key, data, function(error, value) {
        return _this.emit("data:push", [data]);
      });
    });
  };

  return SingletoneWindow;

})(Window);

module.exports = SingletoneWindow;
