// Generated by CoffeeScript 1.4.0
var SlidingTimeWindow, SlidingWindow, Window,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Window = require('./window');

/*
#
# Windows accumulate a subset of a stream. Each window must
# implement the process method and emit "data:push" and "data:pop" events
#
*/


SlidingWindow = (function(_super) {

  __extends(SlidingWindow, _super);

  function SlidingWindow(n) {
    this.n = n;
    this._window = [];
    this._index = {};
    SlidingWindow.__super__.constructor.call(this);
  }

  SlidingWindow.prototype.events = function() {
    return this._window;
  };

  SlidingWindow.prototype.size = function() {
    return this._window.length;
  };

  SlidingWindow.prototype.purge = function() {
    throw new Error("Method must be implemented");
  };

  SlidingWindow.prototype.process = function(data) {
    throw new Error("Method must be implemented");
  };

  return SlidingWindow;

})(Window);

SlidingTimeWindow = (function(_super) {

  __extends(SlidingTimeWindow, _super);

  SlidingTimeWindow.prototype._defaultPurgeInterval = 100;

  function SlidingTimeWindow(n, windowPurgeInterval) {
    this.n = n;
    this.windowPurgeInterval = windowPurgeInterval != null ? windowPurgeInterval : this._defaultPurgeInterval;
    if (this.n < 1) {
      throw new Error("Time interval must be greater than 1");
    }
    SlidingTimeWindow.__super__.constructor.call(this, this.n);
    this._initTicker();
  }

  SlidingTimeWindow.prototype._initTicker = function() {
    var _this = this;
    return this._interval = setInterval(function() {
      return _this.purge();
    }, this.windowPurgeInterval);
  };

  SlidingTimeWindow.prototype.events = function() {
    return this._window.map(function(ev) {
      return ev.data;
    });
  };

  SlidingTimeWindow.prototype.purge = function() {
    var entry, i, now, _events, _i, _len, _ref;
    now = Date.now();
    _events = [];
    _ref = this._window;
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      entry = _ref[i];
      if (now - entry.timestamp >= this.n) {
        _events.push(entry.data);
      } else {
        break;
      }
    }
    if (_events.length > 0) {
      this._window = this._window.slice(i);
      return this.emit("data:pop", _events);
    }
  };

  SlidingTimeWindow.prototype.process = function(data) {
    this._window.push({
      data: data,
      timestamp: Date.now()
    });
    return this.emit("data:push", [data]);
  };

  return SlidingTimeWindow;

})(SlidingWindow);

module.exports = {
  SlidingTimeWindow: SlidingTimeWindow
};
