// Generated by CoffeeScript 1.3.3
var CountStat, MeanStat, MemoryStore, Stat, SumStat, uuid,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

uuid = require('./uuid');

MemoryStore = require('./store').MemoryStore;

Stat = (function() {

  Stat.prototype.id = "stat_interface";

  Stat.prototype.defaultOutputName = "stat_name";

  /*
    constructor : (config) ->#@aggregateField, @outputName=@defaultOutputName) ->
      # create interal id
      @_id = uuid.uuid()
      # set configs
      {@aggregateField, @outputName, @cumulative, @store} = config
      # default output name if needed
      @outputName = @defaultOutputName unless @outputName
      # cumulative by default
      @cumulative = true unless @cumulative isnt null
      # default to memory store
      @store = new MemoryStore() unless @store
  
      throw new Error "Aggregate field must be specified" if not @aggregateField
  */


  function Stat(aggregateField, outputName) {
    this.aggregateField = aggregateField;
    this.outputName = outputName != null ? outputName : this.defaultOutputName;
    if (!this.aggregateField) {
      throw new Error("Aggregate field must be specified");
    }
  }

  Stat.prototype.accumulate = function(currentAggregateValue, newValue) {
    throw new Error("Method must be implemented");
  };

  Stat.prototype.offset = function(currentAggregateValue, oldValue) {
    throw new Error("Method must be implemented");
  };

  return Stat;

})();

SumStat = (function(_super) {

  __extends(SumStat, _super);

  function SumStat() {
    return SumStat.__super__.constructor.apply(this, arguments);
  }

  SumStat.prototype.id = "sum_stat";

  SumStat.prototype.defaultOutputName = "sum";

  SumStat.prototype.accumulate = function(currentAggregateValue, newValue) {
    return currentAggregateValue + newValue;
  };

  SumStat.prototype.offset = function(currentAggregateValue, oldValue) {
    return currentAggregateValue - oldValue;
  };

  return SumStat;

})(Stat);

CountStat = (function(_super) {

  __extends(CountStat, _super);

  function CountStat() {
    return CountStat.__super__.constructor.apply(this, arguments);
  }

  CountStat.prototype.id = "count_stat";

  CountStat.prototype.defaultOutputName = "count";

  CountStat.prototype.accumulate = function(currentAggregateValue, newValue) {
    return currentAggregateValue + 1;
  };

  CountStat.prototype.offset = function(currentAggregateValue, oldValue) {
    return currentAggregateValue - 1;
  };

  return CountStat;

})(Stat);

MeanStat = (function(_super) {

  __extends(MeanStat, _super);

  function MeanStat() {
    return MeanStat.__super__.constructor.apply(this, arguments);
  }

  MeanStat.prototype.id = "mean_stat";

  MeanStat.prototype.defaultOutputName = "mean";

  MeanStat.prototype.accumulate = function(currentAggregateValue, newValue, n) {
    return ((currentAggregateValue * (n - 1)) + newValue) / n;
  };

  MeanStat.prototype.offset = function(currentAggregateValue, oldValue, n) {
    return ((currentAggregateValue * (n + 1)) - oldValue) / n;
  };

  return MeanStat;

})(Stat);

module.exports = {
  Stat: Stat,
  SumStat: SumStat,
  CountStat: CountStat,
  MeanStat: MeanStat
};
