// Generated by CoffeeScript 1.3.3
var CountStat, Stat, SumStat,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Stat = (function() {

  Stat.prototype.id = "stat_interface";

  Stat.prototype.defaultOutputName = "stat_name";

  function Stat(aggregateField, outputName) {
    this.aggregateField = aggregateField;
    this.outputName = outputName != null ? outputName : this.defaultOutputName;
    if (!this.aggregateField) {
      return new Error("Aggregate field must be specified");
    }
  }

  Stat.prototype.accumulate = function(currentAggregateValue, newValue) {
    return new Error("Method must be implemented");
  };

  Stat.prototype.offset = function(currentAggregateValue, oldValue) {
    return new Error("Method must be implemented");
  };

  return Stat;

})();

SumStat = (function(_super) {

  __extends(SumStat, _super);

  function SumStat() {
    return SumStat.__super__.constructor.apply(this, arguments);
  }

  SumStat.prototype.id = "sum_stat";

  SumStat.prototype.defaultOutputName = "sum";

  SumStat.prototype.accumulate = function(currentAggregateValue, newValue) {
    return currentAggregateValue + newValue;
  };

  SumStat.prototype.offset = function(currentAggregateValue, oldValue) {
    return currentAggregateValue - oldValue;
  };

  return SumStat;

})(Stat);

CountStat = (function(_super) {

  __extends(CountStat, _super);

  function CountStat() {
    return CountStat.__super__.constructor.apply(this, arguments);
  }

  CountStat.prototype.id = "count_stat";

  CountStat.prototype.defaultOutputName = "count";

  CountStat.prototype.accumulate = function(currentAggregateValue, newValue) {
    return currentAggregateValue + 1;
  };

  CountStat.prototype.offset = function(currentAggregateValue, oldValue) {
    return currentAggregateValue - 1;
  };

  return CountStat;

})(Stat);

module.exports = {
  Stat: Stat,
  SumStat: SumStat,
  CountStat: CountStat
};
