// Generated by CoffeeScript 1.3.3
var MemoryStore, Stream, Topology, uuid;

MemoryStore = require('../lib/store').MemoryStore;

Stream = require('../lib/stream');

uuid = require('../lib/uuid');

Topology = (function() {

  function Topology() {
    this._store = new MemoryStore();
  }

  Topology.prototype.register = function(id, stream) {
    if (this._store[id] === stream) {
      return;
    }
    if (this._store[id]) {
      throw new Error("Element with id " + id + " already exists in topology");
    }
    return this._store[id] = stream;
  };

  Topology.prototype.deregister = function(id) {
    if (!this._store[id]) {
      throw new Error("Element with id " + id + " does not exists in topology");
    }
    return this._store[id] = null;
  };

  Topology.prototype.get = function(id) {
    if (!this._store[id]) {
      throw new Error("Element with id " + id + " does not exists in topology");
    }
    return this._store[id];
  };

  Topology.prototype.stream = function(spout, outStreamId) {
    if (!spout) {
      throw new Error("Spout required");
    }
    if (!outStreamId) {
      throw new Error("Stream name required");
    }
    return new Stream(spout, outStreamId, this);
  };

  return Topology;

})();

module.exports = Topology;
