// Generated by CoffeeScript 1.3.3
var CHARS, uuid;

CHARS = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'.split('');

uuid = function(len, radix) {
  var chars, i, r, _i, _j;
  chars = CHARS;
  uuid = [];
  radix = radix || chars.length;
  if (len) {
    for (i = _i = 0; _i <= len; i = _i += 1) {
      uuid[i] = chars[0 | Math.random() * radix];
    }
  } else {
    uuid[8] = uuid[13] = uuid[18] = uuid[23] = '-';
    uuid[14] = '4';
    for (i = _j = 0; _j <= 36; i = _j += 1) {
      if (!uuid[i]) {
        r = 0 | Math.random() * 16;
        if (i === 19) {
          uuid[i] = chars[(r & 0x3) | 0x8];
        } else {
          uuid[i] = chars[r];
        }
      }
    }
  }
  return uuid.join('');
};

module.exports = {
  uuid: uuid
};
